####################################################################
#### viya-services-disable.yml                                  ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
#### DISCLAIMER                                                 ####
####################################################################
#### This Ansible Playbook is provided as-is, without warranty  ####
#### of any kind, either express or implied, including, but not ####
#### limited to, the implied warranties of merchantability,     ####
#### fitness for a particular purpose, or non-infringement.     ####
#### SAS Institute shall not be liable whatsoever for any       ####
#### damages arising out of the use of this documentation and   ####
#### code, including any direct, indirect, or consequential     ####
#### damages. SAS Institute reserves the right to alter or      ####
#### abandon use of this documentation and code at any time.    ####
#### In addition, SAS Institute will provide no support for the ####
#### materials contained herein.                                ####
####################################################################
---
- hosts: sas-all
  become: yes
  become_user: root
  gather_facts: False
  any_errors_fatal: true
  vars_files:
    - viya-services-vars.yml
  tasks:
    - name: Find all SAS tenants services
      shell: "{{list_tenant_services_cmd}}"
      changed_when: false
      register: tenants_list_full

    - name: Convert tenants results to ansible variable
      set_fact:
        tenants_services_list: "{{ tenants_list_full.stdout_lines }}"
      when: not ansible_check_mode and tenants_list_full.stdout != ""

    - debug:
        msg: "Tenant services list : {{tenants_services_list}}"
      when: tenants_services_list is defined
        
    - name: Disable SAS Tenants all services from system reboot
      service:
        name: "{{item}}"
        enabled: no
      with_items:
        - "{{tenants_services_list}}"
      when: tenants_services_list is defined  

    - name: Disable SAS Viya all services from system reboot
      service:
        name: sas-viya-all-services
        enabled: no
